// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationMember struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID                   pgtype.UUID        `json:"id"`
	OrganizationID       pgtype.UUID        `json:"organization_id"`
	Name                 string             `json:"name"`
	Description          pgtype.Text        `json:"description"`
	HealthCheckUrl       string             `json:"health_check_url"`
	CheckIntervalSeconds int32              `json:"check_interval_seconds"`
	TimeoutSeconds       int32              `json:"timeout_seconds"`
	FailureThreshold     int32              `json:"failure_threshold"`
	OwnerID              pgtype.UUID        `json:"owner_id"`
	IsPaused             bool               `json:"is_paused"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	FullName       string             `json:"full_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
