// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) (OrganizationMember, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteService(ctx context.Context, id pgtype.UUID) error
	GetOrganization(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetService(ctx context.Context, id pgtype.UUID) (Service, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListOrganizationsByUser(ctx context.Context, userID pgtype.UUID) ([]Organization, error)
	ListServicesByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Service, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
