// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
  organization_id,
  name,
  description,
  health_check_url,
  check_interval_seconds,
  timeout_seconds,
  failure_threshold,
  owner_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, organization_id, name, description, health_check_url, check_interval_seconds, timeout_seconds, failure_threshold, owner_id, is_paused, created_at, updated_at
`

type CreateServiceParams struct {
	OrganizationID       pgtype.UUID `json:"organization_id"`
	Name                 string      `json:"name"`
	Description          pgtype.Text `json:"description"`
	HealthCheckUrl       string      `json:"health_check_url"`
	CheckIntervalSeconds int32       `json:"check_interval_seconds"`
	TimeoutSeconds       int32       `json:"timeout_seconds"`
	FailureThreshold     int32       `json:"failure_threshold"`
	OwnerID              pgtype.UUID `json:"owner_id"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.HealthCheckUrl,
		arg.CheckIntervalSeconds,
		arg.TimeoutSeconds,
		arg.FailureThreshold,
		arg.OwnerID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.HealthCheckUrl,
		&i.CheckIntervalSeconds,
		&i.TimeoutSeconds,
		&i.FailureThreshold,
		&i.OwnerID,
		&i.IsPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getService = `-- name: GetService :one
SELECT id, organization_id, name, description, health_check_url, check_interval_seconds, timeout_seconds, failure_threshold, owner_id, is_paused, created_at, updated_at FROM services
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetService(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.HealthCheckUrl,
		&i.CheckIntervalSeconds,
		&i.TimeoutSeconds,
		&i.FailureThreshold,
		&i.OwnerID,
		&i.IsPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServicesByOrganization = `-- name: ListServicesByOrganization :many
SELECT id, organization_id, name, description, health_check_url, check_interval_seconds, timeout_seconds, failure_threshold, owner_id, is_paused, created_at, updated_at FROM services
WHERE organization_id = $1
ORDER BY name
`

func (q *Queries) ListServicesByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.HealthCheckUrl,
			&i.CheckIntervalSeconds,
			&i.TimeoutSeconds,
			&i.FailureThreshold,
			&i.OwnerID,
			&i.IsPaused,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET
  name = COALESCE($2, name),
  description = COALESCE($3, description),
  health_check_url = COALESCE($4, health_check_url),
  check_interval_seconds = COALESCE($5, check_interval_seconds),
  timeout_seconds = COALESCE($6, timeout_seconds),
  failure_threshold = COALESCE($7, failure_threshold),
  owner_id = COALESCE($8, owner_id),
  is_paused = COALESCE($9, is_paused),
  updated_at = now()
WHERE id = $1
RETURNING id, organization_id, name, description, health_check_url, check_interval_seconds, timeout_seconds, failure_threshold, owner_id, is_paused, created_at, updated_at
`

type UpdateServiceParams struct {
	ID                   pgtype.UUID `json:"id"`
	Name                 pgtype.Text `json:"name"`
	Description          pgtype.Text `json:"description"`
	HealthCheckUrl       pgtype.Text `json:"health_check_url"`
	CheckIntervalSeconds pgtype.Int4 `json:"check_interval_seconds"`
	TimeoutSeconds       pgtype.Int4 `json:"timeout_seconds"`
	FailureThreshold     pgtype.Int4 `json:"failure_threshold"`
	OwnerID              pgtype.UUID `json:"owner_id"`
	IsPaused             pgtype.Bool `json:"is_paused"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.HealthCheckUrl,
		arg.CheckIntervalSeconds,
		arg.TimeoutSeconds,
		arg.FailureThreshold,
		arg.OwnerID,
		arg.IsPaused,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.HealthCheckUrl,
		&i.CheckIntervalSeconds,
		&i.TimeoutSeconds,
		&i.FailureThreshold,
		&i.OwnerID,
		&i.IsPaused,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
